<a href="https://colab.research.google.com/github/Indigo-Coder-github/23_1_Database/blob/feature_plot/DB_yb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#데이터 불러오기
import pandas as pd
import numpy as np
from scipy.stats import zscore
import random as rd
import os


In [32]:
#시각화
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


In [33]:
data=pd.read_csv('/content/HR Employee Attrition.csv')

In [ ]:
data

## 카디널리티 수


In [35]:
print('전체 데이터 건수',len(data))

전체 데이터 건수 1470


## 결측치


In [36]:
print('속성별 결측치 개수')
len(data)-data.count()

속성별 결측치 개수


Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [37]:
print(data.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

우리 데이터에 결측치가 없낭?

## 이상치


In [87]:

for col in data.columns:
    if np.issubdtype(data[col].dtype, np.number):  # 숫자형 데이터만 선택
        zscore_col = zscore(data[col])
        threshold = 3
        print(col, "이상치 개수:", len(np.where(np.abs(zscore_col) > threshold)[0]))

Age 이상치 개수: 0
DailyRate 이상치 개수: 0
DistanceFromHome 이상치 개수: 0
Education 이상치 개수: 0
EmployeeCount 이상치 개수: 0
EmployeeNumber 이상치 개수: 0
EnvironmentSatisfaction 이상치 개수: 0
HourlyRate 이상치 개수: 0
JobInvolvement 이상치 개수: 0
JobLevel 이상치 개수: 0
JobSatisfaction 이상치 개수: 0
MonthlyIncome 이상치 개수: 0
MonthlyRate 이상치 개수: 0
NumCompaniesWorked 이상치 개수: 0
PercentSalaryHike 이상치 개수: 0
PerformanceRating 이상치 개수: 0
RelationshipSatisfaction 이상치 개수: 0
StandardHours 이상치 개수: 0
StockOptionLevel 이상치 개수: 0
TotalWorkingYears 이상치 개수: 16
TrainingTimesLastYear 이상치 개수: 0
WorkLifeBalance 이상치 개수: 0
YearsAtCompany 이상치 개수: 25
YearsInCurrentRole 이상치 개수: 13
YearsSinceLastPromotion 이상치 개수: 42
YearsWithCurrManager 이상치 개수: 14


TotalWorkingYears 이상치 개수: 16   
YearsAtCompany 이상치 개수: 25  
YearsInCurrentRole 이상치 개수: 13  
YearsSinceLastPromotion 이상치 개수: 42  
YearsWithCurrManager 이상치 개수: 14     

ATTRITION=no인 걸로 찾기


### - **이상치를 가지는 카디널리티 출력**

In [ ]:
threshold = 3
outliers = []
for col in data.columns:
    if np.issubdtype(data[col].dtype, np.number):  # 숫자형 데이터만 선택
        zscore_col = zscore(data[col])
        outlier_rows = np.where(np.abs(zscore_col) > threshold)[0]
        outliers.extend(outlier_rows)
outliers = np.unique(outliers)  # 중복 제거
outliers_data = data.iloc[outliers, :]
print(outliers_data)

### TotalWorkingYears 이상치


In [88]:
twy_zscore=zscore(data['TotalWorkingYears'])
threshold=3
outlier_twy = np.where((np.abs(twy_zscore) > threshold)&(data['Attrition'] == 'No'))[0]
outliers_data = data.iloc[outlier_rows, :]
print(outlier_twy)
print("Number of TotalWorkingYears outliers :", len(outlier_twy))

[  85   98  187  270  401  445  624  894  956 1043 1116 1184 1301 1401]
Number of TotalWorkingYears outliers : 14


TotalWorkingYears 즉 총 일한 기간이 높으면 이직을 위한 퇴직이 아닌 명예퇴직 또는 은퇴의 가능성이 높기 때문에 해당 이상치는 빼는것이 적절하다고 생각하다. 

In [ ]:
data_field=data.drop(outlier_twy,axis=0)
print(data_field)

### YearsAtCompany 이상치


In [93]:
yac_zscore=zscore(data['YearsAtCompany'])
threshold=3
outlier_yac = np.where((np.abs(yac_zscore) > threshold)&(data['Attrition'] == 'No'))[0]
outliers_data = data.iloc[outlier_rows, :]


print(outlier_yac)
print("Number of YearsAtCompany outliers :", len(outlier_yac))

[  62   98  190  237  270  411  425  473  477  561  592  653  677  861
  914  918  962 1086 1116 1135 1138]
Number of YearsAtCompany outliers : 21


YearsAtCompany 즉 총 근속기간이 높으면 이직을 위한 퇴직이 아닌 명예퇴직 또는 은퇴의 가능성이 높기 때문에 해당 이상치는 빼는것이 적절하다고 생각하다. 

### YearsInCurrentRole 이상치


In [95]:
yic_zscore=zscore(data['YearsInCurrentRole'])
threshold=3
outlier_yic = np.where((np.abs(yic_zscore) > threshold)&(data['Attrition'] == 'No'))[0]
outliers_data = data.iloc[outlier_rows, :]
print(outlier_yic)
print("Number of YearsInCurrentRole outliers :", len(outlier_yic))

[  63  123  190  231  281  466  716  746  976 1024 1327 1351 1430]
Number of YearsInCurrentRole outliers : 13


###YearsSinceLastPromotion 이상치


In [98]:
yslp_zscore=zscore(data['YearsSinceLastPromotion'])
threshold=3
outlier_yslp = np.where((np.abs(yslp_zscore) > threshold)&(data['Attrition'] == 'No'))[0]
outliers_data = data.iloc[outlier_rows, :]
print(outlier_yslp)
print("Number of YearsInCurrentRole outliers :", len(outlier_yslp))

[  62   64  110  123  178  218  237  326  386  425  427  535  584  653
  701  799  861  875  914  922  926  937  976 1008 1078 1086 1093 1138
 1156 1221 1242 1295 1301 1303 1331 1414]
Number of YearsInCurrentRole outliers : 36


###YearsWithCurrManager 이상치


In [99]:
ywcm_zscore=zscore(data['YearsWithCurrManager'])
threshold=3
outlier_ywcm = np.where((np.abs(ywcm_zscore) > threshold)&(data['Attrition'] == 'No'))[0]
outliers_data = data.iloc[outlier_rows, :]
print(outlier_ywcm)
print("Number of YearsWithCurrManager outliers :", len(outlier_ywcm))

[  28  123  153  187  231  386  561  616  635  686  875  926 1078 1348]
Number of YearsWithCurrManager outliers : 14


###이상치 제외 데이터 필드 생성


In [100]:
outlier_rows = np.concatenate((outlier_twy, outlier_yac,outlier_yic,outlier_yslp,outlier_ywcm)) # 이상치 행 결합
data_field = data.drop(outlier_rows, axis=0)
print(data_field)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0       